### ISSUE TITLE
Ajouter la cartographie dans l'application mobile

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#112]
Modification:
- Créer une page d'affichage de la cartographie
- Créer un service 
La cartographie ne servirait pour le moment que pour la localisation des bornes incendie(si le mode carto est choisit).
- Afficher la cartographie aux coordonnées de l'appareil
- Afficher un pointeur pour indiquer l'endroit choisit
- Enregistrer la position dans tbl_fire_hydrant en geometry

**Comment by iamkinetic** [comment]
@philipperobertgh Ce point-là est-il encore utile?  J'imagine que c'est pas mal ce que tu as fait pour les bornes?
