### ISSUE TITLE
Ajouter la traduction au component de croquis

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip-mobile#116]

**Comment by AudreyLR** [comment]
En attente du Pull Request sur le projet SketchTool et de #75

**Comment by iamkinetic** [comment]
Il y a des conflits à régler, probablement causé par le merge de l'autre pull request.

**Comment by AudreyLR** [comment]
Je ne vois pas de conflit à régler sur la branche de ce repo? Et ils sont réglés du côté de SketchTool.

**Comment by iamkinetic** [comment]
Ouais, mon commentaire visait le repo de SketchTool.  Désolé pour la confusion.
