### ISSUE TITLE
Fix the translation errors within mobile app

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#128]
There are some translation to fix through the mobile app:
 - Parcours -> Choose a fire station in "fr" file 
 - BuildingDetail -> "Détails du batimnet"
 - ...

**Comment by iamkinetic** [comment]
Et je ne ferai pas ce pull request tout de suite parce qu'il contient le pull request de #136 que j'ai rejected.
