### ISSUE TITLE
Fire Hydrant creation

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#15]
Estimate : 4 hours.

When selecting new building's water supply, the user needs to be able to create new fire hydrant.

The mobile page will be a simplified version and won't allow the user to edit the connection.

**Comment by philipperobertgh** [comment]
![Borne par Adresse et rue.png](https://images.zenhubusercontent.com/5ae731e74b5806bc2bd12cbb/0e8bc0b2-9486-4509-b246-89d6d8cfcec2)![Borne par localization et commentaire.png](https://images.zenhubusercontent.com/5ae731e74b5806bc2bd12cbb/834f9c9b-6ab5-4573-878c-5ad3ed0c4f08)

**Comment by philipperobertgh** [comment]
![Borne par Adresse et rue.png](https://images.zenhubusercontent.com/5ae731e74b5806bc2bd12cbb/1f47d537-2120-4470-805f-a15dccbe2b50)

**Comment by iamkinetic** [comment]
J'ai mis à jour l'API pour que les colonnes de type Geometries.Point soient correctement gérées par EFCore et Asp.Net Core.  

Également un custom serializer/deserializer pour qu'on les gèrent en WTK via l'API.
