### ISSUE TITLE
Afficher le contact propriétaire/locataire dans les infos générales 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#157]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/30d16531-0754-43ad-8c39-66848ecffb0d)
https://www.dropbox.com/s/p2avd37vfwn6fv5/Feedback%20Projet-Pilote%20No1.docx?dl=0

**Comment by iamkinetic** [comment]
Est-ce qu'on devrait essayer de faire ça pour la v1 ou ça peut attendre une version subséquente?

**Comment by jocelyncardinal** [comment]
Si possible v1

Le 30 août 2018 à 18:29, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


Est-ce qu'on devrait essayer de faire ça pour la v1 ou ça peut attendre une version subséquente?

**Comment by iamkinetic** [comment]
On va essayer d'entrer ça dans la v1, mais on verra parce que notre liste de point à faire pour la v1 commence à être longue pas mal et nous ne repousserons pas la date plus loin.

**Comment by jocelyncardinal** [comment]
D’accord!  Ce n’est pas « essentiel » … tu l’ajoute dans V1 « si possible » … sinon dans une version subséquente … Note que c’est la même chose pour « Raison Sociale » …

De : iamkinetic <notifications@github.com>
Répondre à : CAUCA-9-1-1/survip-mobile <reply@reply.github.com>
Date : vendredi 31 août 2018 08:42
À : CAUCA-9-1-1/survip-mobile <survip-mobile@noreply.github.com>
Cc : "jocelyn.cardinal@hotmail.com" <jocelyn.cardinal@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [CAUCA-9-1-1/survip-mobile] Afficher le contact propriétaire/locataire dans les infos générales (#157)


On va essayer d'entrer ça dans la v1, mais on verra parce que notre liste de point à faire pour la v1 commence à être longue pas mal et nous ne repousserons pas la date plus loin.
