### ISSUE TITLE
Enregistrer user/password pour permettre le Login automatique (similaire à survi-prototype)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#158]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/4ec4e5a4-75b3-4179-a457-fb421093764e)
https://www.dropbox.com/s/p2avd37vfwn6fv5/Feedback%20Projet-Pilote%20No1.docx?dl=0

**Comment by jocelyncardinal** [comment]
10-4

Le 30 août 2018 à 18:21, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


Clairement, on ne pourra pas avoir une application dans laquelle on ne se log qu'une seule fois parce que ce ne serait pas une bonne idée du côté de la sécurité.

Par contre, la connexion a une durée de plusieurs heures qui fait qu'on ne devrait pas avoir à se logger pendant que notre "authentification" est encore valide.

**Comment by iamkinetic** [comment]
Ceci semble être un plugin approprié pour TouchId, FaceId et lecteur d'empreinte Android:

https://ionicframework.com/docs/native/keychain-touch-id/
