### ISSUE TITLE
Il arrive que l’application « gèle » avec le menu « Liste des inspection » qui s’affiche 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#160]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/8984d148-c470-4617-96b5-ac219947e535)

**Comment by iamkinetic** [comment]
Semble arriver spécifiquement avec iOS.  Ionic mentionne que d'utiliser WkWebView au lieu de UiWebView peut régler les problèmes de ce genre.

De toute façon, WkWebView est la méthode recommandée.

**Comment by iamkinetic** [comment]
J'ai mis 2 heures estimées à ce point, mais je suis parfaitement conscient que c'est le genre de bug qui peut prendre pas mal plus de temps parce qu'on ne sait pas comme le reproduire de façon claire et que la solution est pour l'instant inconnue.

**Comment by mickjol** [comment]
L'erreur à pu être reproduite si le menu s'ouvre à un moment ou l'API ne peux pas répondre.
Erreur précédent ou timeout.

**Comment by mickjol** [comment]
Après plusieurs essaie, je n'ai pas été en mesure de reproduire le problème.
