### ISSUE TITLE
Questionnaire - Lorsqu'on revient en arrière (précédent dans le questionnaire), la réponse ne peut pas être modifié 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#161]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/b882bd79-73f0-419b-9e0f-cdf1ae8bb09b)

**Comment by iamkinetic** [comment]
Sera fait en même temps que #131.
