### ISSUE TITLE
Add pictograms to survip-mobile project for SketchTool

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip-mobile#163]

**Comment by AudreyLR** [comment]
Non, c'est juste quelque chose de temporaire pour que les icones soient disponibles avec que #162 ne soit fait, puisque celui-ci va être plus long à réaliser

**Comment by iamkinetic** [comment]
@AudreyLR Me dire le nombre d'heure pour ce point aussi svp!  Merci.
