### ISSUE TITLE
Utiliser HockeyApp pour notre version de test du mobile

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#165]
Trouver comment plugger ça dans SURVIP-Mobile et faire le setup.

@AudreyLR Vu que vous l'avez fait pour les projets pilotes, peut-être que tu peux nous indiquer comment vous avez fait ça?  On a jamais utilisé HockeyApp ici.

**Comment by AudreyLR** [comment]
Bien sur!

Pour intégrer HockeyApp  à l'application, nous utilisions le package suivant :(https://www.npmjs.com/package/ionic-hockeyapp). Ce n'est pas essentiel pour la distribution, mais ça permet de receuillir les statistiques d'utilisations et de crash.

Pour ajouter d'application sur HockeyApp pour IOS, je faisais d'abord un build pour ios, et utilisais le projet XCode créé pour construire l'archive. 
http://www.joeyt.net/blog/ios-app-distribution-using-hockey-app-tutorial/  était une des bonnes ressources que j'avais trouvé qui explique super clairement les étapes à suivre.

Pour IOS, il faut absolument que les UUID des tous les appareils qu'on veut utiliser soit dans le profil de distribution. On peut les ajouter de la façon suivante avant d'archiver l'application : 
https://support.hockeyapp.net/kb/client-integration-ios-mac-os-x-tvos/adding-new-ios-devices-to-your-provisioning-profile

Pour Android, c'est beaucoup plus facile, j'utilisais Android Studio pour signer l'application et produire le fichier apk uploadé sur HockeyApp de la même façon.
