### ISSUE TITLE
Utiliser le TouchId

### ISSUE THREAD

**Issue by mickjol** [CAUCA-9-1-1/survip-mobile#171]
Ceci semble être un plugin approprié pour TouchId, FaceId et lecteur d'empreinte Android:

https://ionicframework.com/docs/native/keychain-touch-id/

**Comment by iamkinetic** [comment]
@mickjol 

Fenêtre de confirmation d'utilisation de [touchId/FaceId/touch sensor/etc]:
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/744385e3-0f57-422a-b259-1b010d01d954)

Si on fait "Use [sensor]", là on pop l'authentification avec un message comme celui-ci:
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/699358d9-e5f1-44ad-8e04-94ef8ca099fc)
