### ISSUE TITLE
Lors de la reconnexion automatique, certaines choses ne fonctionnent pas bien

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#172]
On perd le nom du user parce qu'il est dans sessionStorage:

On a deux choix pour régler ça:
* Retourner chercher ces infos dans l'API.
* Les mettre aussi dans localStorage au lieu de sessionStorage.

Aussi, le logout ne marche jamais parce qu'on clear sessionStorage alors que le token n'est plus là.

Et la liste des inspections à faire ne se load plus?   À vérifier.  C'est possiblement que c'est parce que je me suis connecté à l'API alors qu'elle utilisait une autre BD et que là mon token ne correspond plus à rien même si il est valide.

**Comment by iamkinetic** [comment]
@mickjol @philipperobertgh si vous avez des problèmes avec l'application mobile, ceci est possiblement la cause.

**Comment by philipperobertgh** [comment]
Le correctif est fonctionnel, il faudrait juste enlever les traces de debug.
