### ISSUE TITLE
Renew or extends user session on modification

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#21]
If the session of the user reach the max amount of time within the session token. If the user is active during his session the token timer must be extended or reset.
Only the unactive users should be redirected to login page.

**Comment by iamkinetic** [comment]
http://piotrgankiewicz.com/2017/12/07/jwt-refresh-tokens-and-net-core/
https://blogs.ibs.com/2017/12/19/token-based-auth-in-asp-net-core-2-part-2-refresh-tokens/

**Comment by iamkinetic** [comment]
Voir comment je l'ai fait dans le projet du 311, ça semble très bien fonctionner.

**Comment by iamkinetic** [comment]
Sera fait via #72 de l'API web.
