### ISSUE TITLE
Starting a refused inspection crash

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#210]
Pour répéter :

Mobile : 
* Répondre au questionnaire d'une nouvelle inspection.
* Compléter l'inspection.

Site web :
* Aller dans le site web et refuser l'inspection.

Mobile de nouveau :
* Redémarrer l'inspection sur le mobile.
* Crash!

![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/d5bbe66c-7c41-4830-8b9e-583cea829b83)

**Comment by philipperobertgh** [comment]
Corrigé dans la point #211Survey-summary-display
