### ISSUE TITLE
Questionnaire - Avertisseur de fumée

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#223]
1 - Où est situé le détecteur, si on sélecitonne "Autre (préciser)", il nous est impossible d'entrer des précisions quant à savoir où est le détecteur  --  En "fouillant" sur le site web, je n'ai pas réussi à ajouter une boite texte pour compléter le questionnaire (Possiblement incompréhension du siteweb) 2018-10-24

2 - Il est impossible de sélectionner "0" (Aucun détecteur présent)

3 - Il est possible de sélectionner "NON" à savoir si le détecteur est alimenté par une pile ou réseau électrique (Si l'un est négatif, l'autre devrait être positif, à moins d'une autre option pour alimenter le détecteur)

4 - Même en inscrivant un étage, que le détecteur est fonctionnel, qu'il est alimenté par une pile, qu'il est relié au central et en ajoutant une notes, il m'est impossible de cliquer sur "Suivante"

**Comment by alexandrelabbe** [comment]
![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/44441183-560b-4549-9f68-ba96fe99464f)

![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/312efc54-dc67-4531-8f60-74c62111cb22)

**Comment by philipperobertgh** [comment]
1 - Où est situé le détecteur, si on sélecitonne "Autre (préciser)", il nous est impossible d'entrer des précisions quant à savoir où est le détecteur -- En "fouillant" sur le site web, je n'ai pas réussi à ajouter une boite texte pour compléter le questionnaire (Possiblement incompréhension du siteweb) 2018-10-24
4 - Même en inscrivant un étage, que le détecteur est fonctionnel, qu'il est alimenté par une pile, qu'il est relié au central et en ajoutant une notes, il m'est impossible de cliquer sur "Suivante"
-> Mauvaise configuration du questionnaire

2 - Il est impossible de sélectionner "0" (Aucun détecteur présent)
-> Voir si la configuration du questionnaire le permet, si oui alors il faudra vérifier la gestion des occurences dans le mobile 

3 - Il est possible de sélectionner "NON" à savoir si le détecteur est alimenté par une pile ou réseau électrique (Si l'un est négatif, l'autre devrait être positif, à moins d'une autre option pour alimenter le détecteur)
 -> Si la question est de savoir pourquoi on utilise pas un checkBox, c'est pour qu'on puisse ajouter des questionsuivantes différentes selon la réponse choisie.

**Comment by iamkinetic** [comment]
@philipperobertgh Est-ce qu'on peut fermer ce point ou on a quelque chose à changer dans l'application?

**Comment by philipperobertgh** [comment]
Il faut valider si la question 2 est belle et bien liée à un problème de configuration du questionnaire. J'ai demandé à Alexandre de revalider les tests pour ce point.

**Comment by alexandrelabbe** [comment]
Je viens de faire le questionnaire, j'ai pu répondre aux questions et me rendre jusqu'à la fin du questionnaire avec succès

Questionnaire fonctionnel
