### ISSUE TITLE
Infos Générale - Transversale

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#226]
* Il est possible de sélectionner la même voie de circulation pour les champs Voie et Transversale.
* Empêcher de changer la valeur lorsque l'inspection n'est pas commencée.

**Comment by iamkinetic** [comment]
Ajouter ce qu'il faut pour empêcher de sélectionner la même rue que la rue du bâtiment.

Ne pas oublier que ce contrôle est utilisé à plusieurs endroits.
