### ISSUE TITLE
Détails du batiment

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#228]
* [x] Faute de frappe dans "détails du bAtÎment

* [x] Le choix de réponse pour "Garage" est en anglais

* [x] Si on tente de quitter la page avant de l'avoir complétée, le message affiché contient une faute de frappe

* [ ] ~~Hauteur, serait-il possible de forcer l'entrer de caractère numériques seulement (Exemple, la ligne D.I.E. si on veut entre un valeur, seulement un clavier numérique est affiché, pourrait-on faire de même pour cette ligne?)~~

* [x] Si on tente de quitter la page avant d'avoir complété, suite à l'avertissement qui est affiché, serait-il possible de faire apparaître en rouge les champs à vérifier / valider? (Aucune image pour ceci)

* [x] Même en ayant entré des données possibles / plausibles dans tous les champs, un avertissement m'est affiché quand je veux quitter la page - Je suis incapable de sauvegarder les données que j'ai entrées

* [ ] ~~Hauteur vs DIE, il est possible d'entrer 014 (Mêtres ou Pieds) pour la hauteur, mais impossible d'entrer 014 pour le D.I.E. Est-ce 0k ainsi? Pourrait-on faire disparaître le 0 qui est affiché par défaut quand on entre une valeur à l'une ou l'autre de ces lignes?~~

* ~~Bâtiment - Type, si on sélectionne autre, devrions-nous avoir une boite texte ou qqch nous permettant d'entrer plus d'information sur le type de bâtiment?~~

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47442523-76940d00-d780-11e8-9382-87a17d01e9ea.png)

![image](https://user-images.githubusercontent.com/44094567/47442534-7b58c100-d780-11e8-941d-425770f53699.png)

![image](https://user-images.githubusercontent.com/44094567/47442546-81e73880-d780-11e8-98f5-dfe150ce18f9.png)

![image](https://user-images.githubusercontent.com/44094567/47442558-890e4680-d780-11e8-8c24-83fc8e2c8e4c.png)

![image](https://user-images.githubusercontent.com/44094567/47442566-8e6b9100-d780-11e8-8761-c75c18ae2e7d.png)

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47442957-5d3f9080-d781-11e8-9040-ec669f9ada92.png)

**Comment by iamkinetic** [comment]
@alexandrelabbe

À propos de ceci "5 - Si on tente de quitter la page avant d'avoir complété, suite à l'avertissement qui est affiché, serait-il possible de faire apparaître en rouge les champs à vérifier / valider? (Aucune image pour ceci)"

C'est clairement un bug parce que les seuls champs obligatoires sont les unités de mesure et seulement lorsqu'on entre un DIE ou une hauteur.

Et il n'y a pas eu de demande d'avoir un champ pour clarifier le "Autre".

**Comment by iamkinetic** [comment]
Concernant le clavier numérique pour la hauteur:
* Sur android c'est bel et bien le clavier numérique qui est utilisé.
* Sur iOS (sur mon XS Max), c'est le clavier complet qui est utilisé.

**Comment by iamkinetic** [comment]
@philipperobertgh @alexandrelabbe  Le DIE est une valeur entière et la hauteur une valeur décimale.  La validation n'est pas la même et c'est pour ça que 014 est permis par un et non par l'autre.

Le clavier numérique est correctement utilisé sur Android et non sur iOS.

J'ai créé le point #254 pour améliorer l'édition des valeurs numériques partout dans l'application mobile.  On mettra alors toute notre énergie à trouver ou faire notre propre composante d'édition numérique qui forcera le bon clavier (si on peut faire) et qui ne permettra pas d'entrer n'importe quoi.  Bref, les points qui concernent l'édition de valeurs numériques en seront pas corrigés pour l'instant.  Ce n'est pas très user friendly en ce moment, mais ça ne peut pas causer de problème non plus parce que la validation me semble quand même solide.
