### ISSUE TITLE
Détails du contact

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#229]
1 - Serait-il possible de faire apparaitre (mettre en évidence) l'endroit où on doit cliquer pour entrer un Nom et Prénom?  Par défaut, je clique sur "NOM" ou "PRÉNOM" pour entrer une données, mais rien ne se passe.  La boîte texte est ~2 cm à côté.
     Nom et Prénom, devrions-nous vérouiller le maximum de caractère qu'on peut entrer? (Un avertissement nous est affiché au 31ième caractère)

2 - Case Priorité, serait-il possible de forcer des caractères numérique, faire afficher seulement le clavier numérique pour cette entrée
      Si on entre plus de 10 caractères, un avertissement nous est affiché.  Pourrait-on faire comme les cases "Extension" et vérouiller le maximum de caractère à 10?

3 - Pour tous les # de téléphone, serait-il possible d'afficher seulement le clavier numérique?
     Pour tous les # de téléphone, on affiche 11 "x" au lieu de 10.  est-ce 0k ainsi?

4 - Le # de téléphone "Autre téléphone" ne se sauvegarde pas

**Comment by iamkinetic** [comment]
Malheureusement on a pas un grand contrôle sur le clavier qui s'affiche à l'édition et le comportement n'est pas toujours le même sur Android que sur iOS.  Aussitôt qu'on met un masque d'édition, le téléphone utilise le clavier complet.  

On va voir ce qu'on peut faire.
