### ISSUE TITLE
Changer enregistrement pour affichage du crop sur web (sketch tool)

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip-mobile#231]
Force l'enregistrement des valeurs de width et height du canvas pour reload après un crop sur web.

**Comment by iamkinetic** [comment]
@AudreyLR Peux-tu ajouter une description au point pour que je sache ce qu'est ce point lorsqu'on fera les releases notes de la prochaine version?

**Comment by iamkinetic** [comment]
Nevermind, le problème vient d'un refactoring de l'API.
