### ISSUE TITLE
La page de confirmation empêche de modifier info 

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#234]
J'entre des informations dans détail du bâtiment et lorsque je quitte la page de confirmation m'empeche de sauvegarder les infos

![Capture d’écran 2018-10-25 à 08.55.14.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/fe132c25-002a-47cb-83df-6cb80e5d3b02)

J'ai essayé plusieurs combinaison et le message apparait toujours.

**Comment by iamkinetic** [comment]
Déjà dans #228
