### ISSUE TITLE
Questionnaire Complété = Message d'erreur

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#235]
La situation s'est produite avec les questionnaires:
Bâtiment principale
PNAP

Quand je répond à toutes les questions, que j'emplie tous les champs diponibles avec des données valables et que je "quitte" le questionnaire, un message d'erreur m'est affiché

Je clique sur "Oui", je reviens dans le questionnaires, les informations entrées sont effacées

**Comment by iamkinetic** [comment]
Pour clarifier : ce que tu appelles "questionnaire" est la fenêtre d'ajout/modification d'un PNAP?

Parce qu'on a une section de l'inspection qui se nomme "Questionnaire" (les questions avec le suivant-précédent).

**Comment by iamkinetic** [comment]
Et quel est le message d'erreur?

**Comment by alexandrelabbe** [comment]
Question #1 = Oui

Question #2 = Voici le message en question:

![image](https://user-images.githubusercontent.com/44094567/47522917-c815c800-d864-11e8-948e-35a88b4c8c22.png)

**Comment by iamkinetic** [comment]
Sera corrigé via #228
