### ISSUE TITLE
Matières Dangereuses

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#236]
1 - Est affichée comme "Hazardous materials" dans la version francophone

2 - Faute de frappe dans l'entête grise, bAtÎment au lieu de bÂtIment

3 - Lorqu'on ajoute un produit et qu'on fait une recheche alphabétique (Ex, Propane), les résultats sont triés par ordre alphabétique, mais le "É" est placé au bas de la liste.  Est-ce 0k ainsi ou le É devrait-il être à la suite du "D"?

4 - Si on entre un "/" dans la barre de recherche, un message d'erreur est affiché (Reproduit à 3 reprises). Aucune erreur avec d'autres symboles

5 - ~~En faisant une recherche manuelle, en défilant vers le bas, la liste arrête à "Acétate de mercure 1629)" Est-ce 0k ainsi?~~

6 - Section "Contenant" - Réservoir.  En quittant le formulaire et en y retournant, l'information vis-à-vis "Réservoir" n'est plus affichée.  Je clique sur le menu déroulant et mon choix est toujours sélectionné/s'affiche à l'arrière du menu déroulant (2 dernières images).  Cette situation se produit lorsqu'on sélectionne "Indéterminé" Les autres choix "demeurent actifs"

7 - Section "Localisation" - Étage - Si on entre des lettres, qu'on quitte les détails et qu'on revient, les lettres entrées sont effacées.  Si on entre des chiffres, qu'on quitte les détaisl et qu'on revient, les chiffres entrés sont encore affichés

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47569140-e6310600-d900-11e8-937b-2e5c98a894fe.png)

![image](https://user-images.githubusercontent.com/44094567/47569183-fea12080-d900-11e8-8333-a8ff8d69ddaa.png)

![image](https://user-images.githubusercontent.com/44094567/47569207-0eb90000-d901-11e8-8c71-292e73be8679.png)

![image](https://user-images.githubusercontent.com/44094567/47569240-1c6e8580-d901-11e8-946d-10b0ad5a50bf.png)

![image](https://user-images.githubusercontent.com/44094567/47569343-5dff3080-d901-11e8-8fb0-5e768ffd021a.png)

![image](https://user-images.githubusercontent.com/44094567/47569364-6eafa680-d901-11e8-863b-aa94b4dc866d.png)

![image](https://user-images.githubusercontent.com/44094567/47569385-82f3a380-d901-11e8-99d0-83a4579fb494.png)

![image](https://user-images.githubusercontent.com/44094567/47569400-8e46cf00-d901-11e8-936d-b1cd6c86f54a.png)

**Comment by iamkinetic** [comment]
@alexandrelabbe

"En faisant une recherche manuelle, en défilant vers le bas, la liste arrête à "Acétate de mercure 1629)" Est-ce 0k ainsi?"

Parce qu'on limite le nombre d'item affiché pour rendre le tout plus rapide. Il faut affiner la recherche pour avoir les résultats voulus.
