### ISSUE TITLE
Protection Incendie - Panneaux d'alarme

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#237]
Je suis incapable de reproduire sur demande / je n'ai aucune recette pour recréer la situation, mais il y arrive, lorsqu'on modifie le "Type" du panneau d'alarme, qu'on clique sur la flèche ![image.png](https://images.zenhubusercontent.com/5bc0bfd06448de0e34649262/7aa48086-825f-4f81-933e-cfd57747d911) et qu'on revienne dans le panneau d'alarme que le "Type" soit effacé pour 2 à 4 secondes et que le Type s'affiche à nouveau

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47571284-2d6dc580-d906-11e8-8956-b3f41812ea3b.png)

![image](https://user-images.githubusercontent.com/44094567/47571352-51310b80-d906-11e8-9045-a14a0ba518fe.png)

**Comment by iamkinetic** [comment]
Vérifier rapidité de la requête

**Comment by iamkinetic** [comment]
La requête est rapide.  Par contre, j'ai remarqué qu'on affichait jamais le wait form (même si on le préparait correctement), ce qui pouvait donner une drôle d'impression.

Il peut toujous arriver qu'une requête soit plus longue et le waitform montrera qu'il se passe quand même quelque chose.
