### ISSUE TITLE
Message Erreur - Période Inactivité

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#238]
De façon aléatoire, ce message m'est affiché quand je suis quelques minutes sans me servir de l'application.

Suite à ce message, "la roue" tourne sans fin.  Application non utilisable, je dois la fermer et l'ouvrir à nouveau.

Y'a-t-il un "timer" lié à l'inactivité de l'application?  Sera-t-il de modifier la situation?  Faire apparaître un message comme quoi on a été débranché automatiquement, nous rammener à l'écran de branchement?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47576460-893e4b80-d912-11e8-9ab3-e590e2bbb60c.png)

**Comment by philipperobertgh** [comment]
@alexandrelabbe Ce problème a-t-il été reproduit plusieurs fois ? Sur les 2 plateformes ou juste IOS ?

**Comment by alexandrelabbe** [comment]
@philipperobertgh Plus d'une fois oui (2 fois la semaine dernière lors de mes tests).  J'ai seulement un iPhone, impossible pour moi de tester l'autre plateforme

**Comment by philipperobertgh** [comment]
@alexandrelabbe Il faudrait que tu me donnes plus de détails sur les actions que tu fais, car pour le moment je n'ai pas réussit à le reproduire.

**Comment by alexandrelabbe** [comment]
Allo Philippe
Je n'ai aucune recette exacte, désolé.  La situation est/était vraiment "aléatoire".
Tout ce dont je me rappel (et que je viens d'essayer, sans succès), c'est que le cellulaire était en veille quelques instants avant d'avoir le message.
Je fais d'autres vérification, si je trouve quoi que ce soit, je te fais signe

**Comment by iamkinetic** [comment]
C'est corrigé ça finalement??

**Comment by philipperobertgh** [comment]
@iamkinetic Comme discuté hier je n'ai pas réussit à reproduire le problème que ce soit en "Test" ou en "Dev", donc non il n'est à priori pas réglé. Cependant j'ai fait quelques optimisations concernant l'affichage lors des rafraichissements.

**Comment by alexandrelabbe** [comment]
Philippe?  Quelque chose vient de me sauter à la figure.  Sur l'image ci-haut, connexion internet est "LTE"  J'étais / je suis généralement branché sur le wifi du central.  Ce n'est qu'un hypothèse, mais serait-il possible que la situation ait été causée lorsque "je perdais le wifi" ou lorsque je m'y branchait à nouveau?

C'est la seule piste que j'ai pour l'instant
