### ISSUE TITLE
Bâtiment Principale - Anomalies 

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#240]
1 -Quand je tente de supprimer une anomalie que je viens de créer, un message d'erreur est affiché
    Si je supprime l'image associée à l'anomalie, je peux supprimer l'anomalie sans pépin

2 - Est-il possible de supprimer un thème qu'on vient de créer?

**Comment by iamkinetic** [comment]
@alexandrelabbe le thème existe tant qu'il y a des anomalies de ce thème.

**Comment by alexandrelabbe** [comment]
Effectivement, le thème a été supprimé après avoir supprimé l'image et l'anomalie!  Il n'est plus disponible non plus si on ajoute une anomalie!

**Comment by iamkinetic** [comment]
Vérifier si on sort les thèmes inactifs.

**Comment by philipperobertgh** [comment]
Problème situé dans la suppression des images dans la mauvaises collection.
-> API
