### ISSUE TITLE
Menu non disponible

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#241]
J'ignore comme reproduire la situation, mais ça fait quelques fois que ça se produit

Je sélectionne un bâtiment pour l'inspection (1517 Chemin Fecteau) et quand je clique sur les 3 lignes coin supérieur gauche, un menu vide est affiché.  Impossible de sélectionner quoi que ce soit.

Je dois quitter l'inspection et y revenir pour accéder aux menus

**Comment by iamkinetic** [comment]
Nous avons fait quelques optimisations dans la gestion d'erreur et dans la gestion de la connexion au serveur qui auront potentiellement réglé ce problème que nous n'avons pu reproduire.

Je vais me permettre de le fermer, mais sentez-vous bien libre de le réouvrir ou d'en créer un nouveau si vous pouvez à nouveau reproduire le problème après la prochaine mise à jour.
