### ISSUE TITLE
Liste des bornes incendie - Ajout/Modification Borne

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#242]
Parmis les couleurs disponibles pour une borne fontaine, nous avons la couleur blanche. Si on sélectionne cette couleur, le "crochet de validation" est blanc également, il "disparaît" / est invisible

Même chose pour les bornes incendies disponibles, si elle sont blanches, le "logo" de borne fontaine est invisible.

Image # 1 = Crochet sur fond noir
Image # 2 = Crochet sur fond blanc
Image # 3 = Logo insivible

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47668441-d6265a00-db7e-11e8-9bb6-a620dde8d54f.png)

![image](https://user-images.githubusercontent.com/44094567/47668576-32897980-db7f-11e8-892a-f7987d09af3d.png)

![image](https://user-images.githubusercontent.com/44094567/47668609-4634e000-db7f-11e8-813f-3a3e36a7ddbb.png)

**Comment by iamkinetic** [comment]
@alexandrelabbe Hmmm.... Des suggestions pour régler ça?  Je doute fort qu'on puisse avoir une couleur de crocher différente pour chaque couleur.

**Comment by alexandrelabbe** [comment]
Gris?

**Comment by iamkinetic** [comment]
Sera corrigé via #263.
