### ISSUE TITLE
Borne Fontaine - Détails de la borne

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#243]
1 - Il est possible, dans la section "Débit" et "Pression" de mettre une valeur "De" inférieur à la valeur "À", est-ce 0k ainsi?

2 - Section "Localisation", si on change le "Type" de "Adresse" à "Rue Intersection", il est impossible de faire afficher une valeur vis-à-vis "Voie"

3 - Suite au point # 2, si on clique sur "Back" et qu'on revient dans la même borne, les données entrées dans les sections "Débit" et "Pression" sont disparues.  N.B. Cette situation m'est apparue 2 fois, mais j'ignore comme la reproduire exactement.

4 - Si on crée une nouvelle borne, il est possible de sélectionner la même voie pour les champs "Voie" et "Transversale"

5 - Si on entre un "/" dans la barre de recherche pour les voies de circulation, un message d'erreur est affiché

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47673018-cceeba80-db89-11e8-8bc5-0228bf8008fa.png)

![image](https://user-images.githubusercontent.com/44094567/47673043-e3951180-db89-11e8-8b3b-9aeaac2f9e5c.png)

![image](https://user-images.githubusercontent.com/44094567/47673082-fad3ff00-db89-11e8-8906-464abe763b1e.png)

![image](https://user-images.githubusercontent.com/44094567/47673106-13dcb000-db8a-11e8-8338-ecf8dc33f497.png)

![image](https://user-images.githubusercontent.com/44094567/47673133-2820ad00-db8a-11e8-9399-38b6b943fff5.png)

**Comment by iamkinetic** [comment]
Sera corrigé dans #263.
