### ISSUE TITLE
Parcours

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#245]
1 - Détail du parcours, on affiche "Back" en haut à gauche, pourrions nous traduire ?

2 - Détails de la voie, affiche "Back" en haut à gauche

3 - Si on entre un "/" dans le champ de recherche pour la voie de circulation, un message d'erreur nous est affiché

4 - Détails du parcours, on peut sélectionner la même voie de circulation l'une à la suite de l'autre, est-ce 0k ainsi?

5 - Une fois la voie sélectionnée, "Tout droit" n'est pa affiché entre parenthèse contrairement à Gauche et Droige

6 - Détails du parcours, devrions-nous ajouter un bouton "Annuler"?

7 - Parcours, si plus d'un parcours disponible par caserne, devrions-nous pouvoir identifier chaque parcours, ajouter un nom ou un identifiant par parcours créé?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47728053-f8c67a80-dc33-11e8-970e-ea74b343dab5.png)

![image](https://user-images.githubusercontent.com/44094567/47728093-0f6cd180-dc34-11e8-98a3-ac2c7df71d01.png)

![image](https://user-images.githubusercontent.com/44094567/47728143-257a9200-dc34-11e8-9f27-981e7d624bd9.png)

![image](https://user-images.githubusercontent.com/44094567/47728236-4e028c00-dc34-11e8-955d-d992b913ca39.png)

![image](https://user-images.githubusercontent.com/44094567/47728293-6e324b00-dc34-11e8-981f-f9f9e48e9fc4.png)

![image](https://user-images.githubusercontent.com/44094567/47728340-899d5600-dc34-11e8-8fbd-eaafeb932c78.png)

![image](https://user-images.githubusercontent.com/44094567/47728361-98840880-dc34-11e8-9378-237905739e3c.png)

**Comment by iamkinetic** [comment]
@alexandrelabbe

1 - Détail du parcours, on affiche "Back" en haut à gauche, pourrions nous traduire ? **oui**

2 - Détails de la voie, affiche "Back" en haut à gauche ** oui **

3 - Si on entre un "/" dans le champ de recherche pour la voie de circulation, un message d'erreur nous est affiché ** ce sera corrigé **

4 - Détails du parcours, on peut sélectionner la même voie de circulation l'une à la suite de l'autre, est-ce 0k ainsi? ** ce sera à voir où est la ligne entre validation et survalidation **

5 - Une fois la voie sélectionnée, "Tout droit" n'est pa affiché entre parenthèse contrairement à Gauche et Droige ** volontairement **

6 - Détails du parcours, devrions-nous ajouter un bouton "Annuler"? ** non, car ce n'est pas une action possible.  Tous les changements sont sauvegardés au fur et à mesure qu'ils sont effectué. **

7 - Parcours, si plus d'un parcours disponible par caserne, devrions-nous pouvoir identifier chaque parcours, ajouter un nom ou un identifiant par parcours créé? ** Ce n'est pas une vilaine idée, mais on est déjà beaucoup plus flexible que dans la version RAO.  Qu'en penses-tu @jocelyncardinal ? Devrions-nous faire ça ou on attend d'avoir une demande en ce sens? **

**Comment by iamkinetic** [comment]
À corriger:
* Localizations manquantes;
* / qui fait planter la recherche.

**Comment by jocelyncardinal** [comment]
Voici mon feedback ...

Point 1 - low priority
Point 2 - low priority
Point 3 - low priority
Point 4 - Pas de validation nécessaire 
Point 7 - On attend de voir si demande en ce sens

**Comment by iamkinetic** [comment]
On a corrigé le "/" dans la recherche dans un autre point et on va corriger les traductions manquantes via un autre point.
