### ISSUE TITLE
"Accueil" - Configuration

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#246]
À quoi sert le bouton "Configurations", comment fait-on pour l'activer / l'utiliser?

Est-ce 0k que ce soit au pluriel?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47730586-dc790c80-dc38-11e8-8142-06d20934d81c.png)

**Comment by iamkinetic** [comment]
Le bouton est disabled pour l'instant parce qu'on a pas fait de configuration modifiable.

On va peut-être finir par l'enlever si on a rien.  On parlait de mettre la langue modifiable par là au début, mais finalement on prend la langue de l'appareil.
