### ISSUE TITLE
Liste des bornes incendie

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#247]
1 - Pour un # civique, il est possible d'associer plus d'une fois la même borne fontaine au # civique.

2 - Les bornes semble se place par ordre alphanumérique, est-ce 0k ainsi?  Devrions-nous permettre de "changer l'ordre" d'apparition des bornes?

**Comment by iamkinetic** [comment]
Simplement faire la correction pour ne pas permettre de sélectionner deux fois la même borne.  On ne touchera pas à l'ordre des bornes qui est effectivement en ordre alphanumérique (ce qui est le plus logique puisque le numéro est alphanumérique).

**Comment by iamkinetic** [comment]
Sera fait via #263.
