### ISSUE TITLE
Quitter puis se Connecter à nouveau à l'application

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#248]
1 - Quand on quitte l'application et qu'on la charge à nouveau en moins d'1 minute (je n'ai pas le délai exacte), l'appliation se charge et nous rebranche automatiquement.  Étant donné qu'on a quitté l'application, devrait-elle nous demander notre nom utilisateur + mot de passe à nouveau?

2 - J'ignore si possible ou non, mais quand l'application se charge, on a une fenêtre avec "Please wait", devrions-nous/est-ce possible de traduire?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47735875-c15fca00-dc43-11e8-8538-4cd6c0711fac.png)

**Comment by iamkinetic** [comment]
L'application va en effet se reconnecter automatiquement lorsque c'est possible.  C'est volontairement codé pour ça.

On va regarder pour la traduction du "please wait..." dans un autre point.
