### ISSUE TITLE
Application Paysage vs Portrait

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#249]
Il est possible de lancer l'application en mode "Paysage", l'affichage est "mal cadré"  Devrait-on utiliser l'application en mode portrait seulement?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/47738249-236efe00-dc49-11e8-8de6-d47fd093cd37.png)

![image](https://user-images.githubusercontent.com/44094567/47738271-308bed00-dc49-11e8-909d-a2504aac436f.png)

**Comment by iamkinetic** [comment]
Pour l'image de fond, c'est juste parce qu'on a pas fait les images pour paysage, donc il utilise l'image de portrait et fait ce qu'il peut.

Pour le texte de côté, c'est certaintement weird et je ne sais pas trop si on a du contrôle là dessus.

**Comment by iamkinetic** [comment]
Effectivement que les messages qui ont ce problème sont hors de notre contrôle.  Ce sont des messages iOS ou Android.

@Jocelyncardinal Est-ce qu'on devrait bloquer l'orientation de l'application pour ne permettre que "portrait"?
