### ISSUE TITLE
Questionnaire - Il faut completer deux fois avant d'etre autoriser a compléter l'inspection

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#253]

**Comment by iamkinetic** [comment]
Compléter deux fois avant d'être autoriser à compléter?  Qu'est-ce que ça veut dire?

**Comment by iamkinetic** [comment]
@philipperobertgh on close ce point?

**Comment by philipperobertgh** [comment]
Pas réussit à reproduire le problème en DEV.

**Comment by jocelyncardinal** [comment]
Si ça peut aider j’ai reproduit le problème sur le 617, rue des muguets... le questionnaire a été complété et j’ai le message ... tu peux te logger sur Jocelyn.cardinal pour l’essayer - Frédéric connaît mon password secret :)

[image5.png]







Le 1 nov. 2018 à 12:50, iamkinetic <notifications@github.com<mailto:notifications@github.com>> a écrit :


@philipperobertgh<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fphilipperobertgh&data=02%7C01%7C%7C6bef0098fb044506300808d6401a108d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636766878015960831&sdata=0stJGSnV7Avl9gmCO6GUYMi1X3z6u4H2h2aiLokyzwM%3D&reserved=0> on close ce point?

**Comment by philipperobertgh** [comment]
Vérifié avec l'adresse 617, rue des muguets, la version de dev actuelle complète parfaitement l'inspection

**Comment by jocelyncardinal** [comment]
Super!!! Bonne idée d’avoir tester l’adresse avec lapp en dev. Ça prouve que le problème est réglé

Le 2 nov. 2018 à 08:42, Phil <notifications@github.com<mailto:notifications@github.com>> a écrit :


Vérifié avec l'adresse 617, rue des muguets, la version de dev actuelle complète parfaitement l'inspection

**Comment by iamkinetic** [comment]
Je ne crois pas que ça prouve quoi que ce soit, mais on verra bien si le problème arrive encore avec la nouvelle version! ;)
