### ISSUE TITLE
Survey's page doesn't always save correctly?

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#269]
*We have this configuration :*
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/f89ea59c-ba0d-423e-9f2c-9198d0d32840)
The question is "text" type question.

*And this is what shows up in the report:*
![image.png](https://images.zenhubusercontent.com/5ad793b54b5806bc2bcfaab3/6ab6f223-d218-47c5-a878-124e4749ad64)
The answer is an id.  This id is from a choice from another question.

At first we thought the report query wasn't ok, but it is.  The problem seems to be in the mobile :
* Is the answer kept when changing a previous answer and wrongfully used later on?
* Has the survey been modified since the moment it has been answered?

**Comment by iamkinetic** [comment]
@jocelyncardinal Nous n'avons pas l'intention de mettre des efforts là dessus pour ce sprint, mais peut-être que tu pourrais expliquer le problème à Alexandre et qu'il pourrait mettre un peu de temps pour voir s'il est capable de le reproduire.  Qu'en dis-tu?

**Comment by jocelyncardinal** [comment]
Oui bonne idée! Je vais voir avec lui pour reproduire le bug sur l'app mobile (iOS et Android) ...

**Comment by iamkinetic** [comment]
Je vais fermer ce point vu qu'on a aucune nouvelle du bug depuis un mois.
