### ISSUE TITLE
Quitter - "Please wait"

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#270]
Version mise à jour ce matin
1 - J'ouvre l'application, j'étais déjà brancher, je clque sur les "3 barres" en haut à gauche, je clique sur "Quitter".  Le message "Please wait" avec la roue qui tourne m'est affiché.

Après 2 minutes, la roue tourne toujours

Je "kill" l'application, m'y reconnecte, fait les 3 barres, clique sur "Quitter", même situation
"Please wait" avec la roue

2 - Serait-il possible de traduire "Please wait"?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/48359508-20bdd100-e66b-11e8-86c4-a1da24489496.png)

**Comment by iamkinetic** [comment]
J'ai répété le problème sur mon iPhone, le bouton quitter ne quitte plus...
