### ISSUE TITLE
Refus Visite - Nouvelle Date Visite

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#271]
1 - Il est possible d'entrer et de sauvegarder une "Nouvelle date de visite" antérieure à la date actuelle

Devrions-nous refuser ce genre d'entrée?

2 - Le bouton "Refus du propriétaire", à quoi sert-il? (Flèche bleu)

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/48443259-7d4de880-e75e-11e8-9891-9c5037598070.png)

**Comment by iamkinetic** [comment]
Que tu fasses "absence" ou "refus", c'est la même fenêtre qui pop (celle du screenshot).  Quand on prend refus, on met le "refus" par défaut à "vrai" et on ne permet pas de le changer.

En tant que tel, la seule utilité est de montrer que l'annulation de la visite a lieu à cause du refus.  Si tu fais "absence", tu pourras voir que "refus" n'est pas activé.

**Comment by iamkinetic** [comment]
À corriger :
* Mettre la valeur minimale de la date à "aujourd'hui".
