### ISSUE TITLE
Détails du contact

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#273]
1 - Téléphone domicile - Doit-on vraiment avoir la possibilité d'entrer un # d'extension pour un # à domicile?
     Si oui, le # d'extension, le format semble erroné

2 - Même avec toutes les cases complétées avec des données valides, dès qu'on cliquer sur le " < " pour revenir en arrière, un message

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/48576263-0f322e80-e8e2-11e8-9def-1b134e8d5b9f.png)

![image](https://user-images.githubusercontent.com/44094567/48576707-350c0300-e8e3-11e8-9e48-f88e3c8d79e3.png)

**Comment by iamkinetic** [comment]
C'est une bonne question pour l'extension maison, mais je dois dire que j'ai copié ce qu'on avait dans Admin v1 et v2 pour les # de téléphone des contacts.
