### ISSUE TITLE
Image "Chargement Application"

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#274]
L'image affichée lors du chargement de l'application ne prends pas l'écran en entier, on voit une barre blanche au bas de l'image

est-ce 0k ainsi?

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/48715159-60903580-ebe2-11e8-8f56-d72b5422ddbf.png)

**Comment by iamkinetic** [comment]
@alexandrelabbe Quel est le modèle du téléphone que tu utilises déjà?

**Comment by alexandrelabbe** [comment]
iPhone6 = A1549
