### ISSUE TITLE
Contact du Bâtiment

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#275]
Pour ces tests, j'entre "A" comme Prénom et "B" comme Nom

1 - Il est possible de sauvegarder un contacte en entrant seulement un nom et un prénom (Aucun #)

2 - # Télévertisseur, si on entre un # uniquement dans cette cellule, qu'on clique sur le "<", un avertissement nous est affiché.  On clique sur "Non", on clique à nouveau sur le "<", on peut sortir des détails l'avertissement n'est plus affiché

2.1 - Si on met une lettre minuscule comme première lettre du nom de famille et qu'on répète l'étape ci-haut, aucun avertissement n'est affiché quand cliquant sur le "<"

3 - # Téléavertisseur, cette case fait afficher un avertissement, même avec un # valide avec ou sans # d'extension

Question; il est possible de mettre le même # à toutes les lignes (Domicile, Cellulaire, Téléavertisseur, Autre), est-ce 0k ainsi? 

4 - Si on veut corriger un numéro, on clique sur le # à l'endroit où on veut faire la correction, on peut entrer la correction et le curseur est automatiquement déplacé à la fin du #.  A titre d'exemple, on entre le 123 456 7890  On veut remplacer le 4 par le 8, on clique "en avant du 4", on entre "8", le # devient alors le 123 845 6789  Un avertissement nous indique également que "Le numéro doit être composé d'au minimum 10 chiffres"

**Comment by iamkinetic** [comment]
Nous avons déjà un point pour se créer une composante d'entrée de valeur numérique qui sera mieux faire, qui affichera le bon clavier pour la situation et qui ne permettra plus d'entrer des valeurs qui n'ont pas de sens pour ensuite afficher un message pour dire que la valeur entrée n'est pas bonne.

Nous ne ferons donc pas de changement à ce niveau-là en attendant cette composante.

Voir #254
