### ISSUE TITLE
SketchTool - Corriger la sélection boutons

### ISSUE THREAD

**Issue by AudreyLR** [CAUCA-9-1-1/survip-mobile#282]
Plusieurs boutons peuvent être sélectionnés en même temps.

**Comment by iamkinetic** [comment]
@AudreyLR J'imagine qu'on peut comprendre que la même correction sera automatiquement fait dans l'application web dès qu'on mettra à jour le package npm?

**Comment by AudreyLR** [comment]
Oui, ça va être sur la même branche que les tooltips.

Le ven. 14 déc. 2018 à 09:51, iamkinetic <notifications@github.com> a
écrit :
