### ISSUE TITLE
Anomalie - Ajouter une anomalie

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#286]
**L'application gèle**

**To Reproduce**
- Aller dans "ANOMALIES DU BÂTIMENT"
-Cliquer sur "Ajouter"
-Thème: Je sélectionne "Détecteur de fumée"
-Notes: J'entre du texte
-Photo(s): Je clique sur "Nouvelle.."
-Je prend une photo
-Valider

L'application gèle, je dois la fermer et redémarrer

**Expected behavior**
Que ça gèle pas?

**Screenshots**
Oui

**Desktop (please complete the following information):**
Non applicable

**Smartphone (please complete the following information):**
iPhone6 - Modèle A1549
Version - IOS 12.1

**Additional context**
Tester 3 fois, la même situation est facile à reproduire
La situation est la même si on clique sur "Choisir" au lieu de "Nouvelle.." L'application "gèle" et ne peut plus être utilisée

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/49881416-52f25800-fdfc-11e8-987b-c43fd730918c.png)

**Comment by iamkinetic** [comment]
Cas répété sur iphone XS Max avec 1.3 dans l'environnement de test.

**Comment by iamkinetic** [comment]
Bug également présent dans les risques particuliers, mais tout fonctionne correctement pour le plan d'implantation.

**Comment by iamkinetic** [comment]
@philipperobertgh As-tu ce bug sur Android?

**Comment by iamkinetic** [comment]
Ok, problème trouvé!

**Comment by iamkinetic** [comment]
Corrigé et version released (1.3.1).
