### ISSUE TITLE
L'application ne se "débranche" plus automatiquement

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#288]
J'ai fermé l'application, laissé passé du temps (+ de 10 minutes) et en ouvrant l'application à nouveau, je suis toujours branché.  Comme si l'application ne se débranche plus automatiquement après un délai de X minutes

Est-ce voulu ainsi?

iPhone 6: Modèle A1549
Verions iOS: 12.1.1 (16C50)
SURVI-Prévention: Denière mise à jour (Où peut-on voir la version de l'application?)

**Comment by iamkinetic** [comment]
@alexandrelabbe
La version n'est pas affichée pour l'instant, on s'est justement créé un point pour l'afficher sur l'application mobile et sur le site web.

Voici le fonctionnement pour la connexion :
Quand tu te connectes (avec username/password, TouchId ou FaceId), le serveur te retourne deux trucs différents : un jeton d'accès qui te donne accès au serveur pendant 2 heures et un jeton de "refresh" qui te permet d'avoir un nouveau jeton d'accès lorsqu'il devient échu pendant x heures (je crois que j'ai mis 8 heures pour l'instant).

Donc normalement, tu devrais pouvoir te connecter une seule fois pendant une journée si l'application n'est pas sortie de la mémoire.

**Comment by alexandrelabbe** [comment]
10-4 c'est noté

Merci pour l'information
