### ISSUE TITLE
Firehydrant : make sure the geolocalization fields are always available 

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#291]
Il faut enlever le mode "Geolocalisation" des types d'adresse possible pour une borne.  La géolocalisation deviendra disponible en tout temps.

Il ne faut pas oublier d'enlever le code qui réinitialise la coordonnée quand on change de type d'adresse.

S'assurer que les transversales soient nommées ainsi et non "intersection".

**Comment by iamkinetic** [comment]
@jocelyncardinal Note ce changement que nous ferons pour se rapprocher un peu plus du fonctionnement du logiciel Cauca.

**Comment by iamkinetic** [comment]
@jocelyncardinal J'ai envie de carrément fermer ce point et d'en créer un nouveau si on a un jour la demande de pouvoir créer des bornes par l'application mobile.  Qu'en penses-tu?

**Comment by jocelyncardinal** [comment]
D’accord
