### ISSUE TITLE
Liste des bornes incendie vs Détails de la borne

### ISSUE THREAD

**Issue by alexandrelabbe** [CAUCA-9-1-1/survip-mobile#292]
**Numéro de la borne est différent d'une page à l'autre**
Plusieurs 0 sont ajoutés avant le Numéro de la borne

**To Reproduce**
1. Allez à "Liste des bornes incendie"
2. Cliquez sur "Ajouter..."
3. Cliquez sur "Crée une nouvelle borne..."
4. Type, sélectionnez "Borne Fontaine"
5. Numéro, entrez des lettres (Exemple: Quatorze)
6. Sélectionnez une couleur
7. Dans le fond, emplissez tous les champs avec ce que vous voulez
...
X. Lors que la borne s'affiche dans la "Liste des bornes incendie", il y a une série de caractères inscrit avant le Numéor de la borne

**Expected behavior**
Afficher seulement le numéro, sans caractère supplémentaire

**Screenshots**
Oui

**Desktop (please complete the following information):**
Non, utilise un smartphone

**Smartphone (please complete the following information):**
iPhone 6
 - iOS 12.1.1 (16C50)

**Additional context**

**Comment by alexandrelabbe** [comment]
![image](https://user-images.githubusercontent.com/44094567/49954701-0d528f80-fecf-11e8-92d7-2d8ab0deeced.png)

**Comment by iamkinetic** [comment]
Oops, c'est la couleur en hexadécimal!

Probablement du code de debug qui traîne.

**Comment by iamkinetic** [comment]
Fixed via #301
