### ISSUE TITLE
Allow user to use the application even when the API is not reachable

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#304]
* [x] L'usager doit au moins se connecter une fois.
* [x] Si le serveur est indisponible et qu'on a un token, on le considère comme connecté.
* [x] Quand on essaie d'accéder au serveur et qu'on a un 401 avec refresh token expiré, on va au login.

**Comment by iamkinetic** [comment]
@jocelyncardinal @Zalverick @philipperobertgh 

Comment est-ce qu'on gère le login dans une application qui a un mode hors ligne?

**Comment by iamkinetic** [comment]
Merci pour vos réponses éclairantes! ;)

**Comment by jocelyncardinal** [comment]
Voici quelques idées en rafales …
 
L’usager doit obligatoirement se logger en mode « en ligne » pour mettre l’application en mode hors-ligne.
Une fois que l’application est en mode hors ligne, l’usager n’aurait plus besoin de se logger car l’application aura sauvegardé le nom d’utilisateur (login user) localement sur le mobile (attention on ne sauvegarde pas le password localement)  
Lorsque l’usager veux revenir à nouveau en mode « en ligne, il devra se relogger user/password sur le serveur avec le même nom d’utilisateur (login user)
