### ISSUE TITLE
Allow user to send completed inspection to API

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#306]
* [x] Créer une fonction qui upload les trucs modifiés de la cache vers API.
* [x] Caller cette fonction quand on fait "Refuser visite" ou "Absence" ou "Compléter visite" ou "Transmettre au serveur".
* [x] Supprimer l'inspection de la cache lorsque le transfert s'est effectué avec succès.
* [x] L'inspection refusée aparait "à transférer" lorsque downloadé.

**Comment by philipperobertgh** [comment]
* [ ] Enlever commentaire dans FireHydrantService et FireHydrantController.
* [ ] Fonction AddOrUpdatePicture dans InspectionBuildingAnomalyService n'est appelé de null part et n'est pas override.

**Comment by iamkinetic** [comment]
En attente que #307 soit merged.
