### ISSUE TITLE
Make the map available offline in the fire hydrant's edition page

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#308]

**Comment by iamkinetic** [comment]
@jocelyncardinal Est-ce que ça vaut la peine qu'on mette l'effort pour faire marcher la carto en mode hors ligne pour pouvoir permettre l'ajout de nouvelle borne dans l'application mobile?

**Comment by iamkinetic** [comment]
@jocelyncardinal si c'est non, je vais me permettre de fermer ce point.

**Comment by jocelyncardinal** [comment]
Réponse: non pas besoin d’accéder la carton en mode hors ligne.
