### ISSUE TITLE
Cannot see the Fire Hydrant list in App Mobile and Web site (NO BUG)

### ISSUE THREAD

**Issue by jocelyncardinal** [CAUCA-9-1-1/survip-mobile#322]
**Describe the bug**
Cannot see the Fire Hydrant list in App Mobile and Web site

**Screenshots**
From the App Mobile ...
![Capture d’écran 2019-03-14 à 12.27.19.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/87304dc5-caef-4191-b7f3-37cee8cba7f0)

... to the Web site for approbation ...

![Capture d’écran 2019-03-14 à 11.55.10.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/62ff4380-c70c-4cfe-875f-43bbabb96f67)

**Comment by jocelyncardinal** [comment]
**OK, THERE IS NO PROBLEM !  I just realize that I need to select the Fire Hydrant to associate with the address.

**Comment by iamkinetic** [comment]
Yup.  Peut-être qu'on devrait changer les titres ou ajouter une description pour clarifier le tout?

**Comment by jocelyncardinal** [comment]
ouin exact, laisse l'issue ouvert pour le temps qu'on y pense et que je demande l'avis de pompiers au besoin ...
