### ISSUE TITLE
Questionnaire - For groups of questions the minimum and maximum occurrence does not work

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#338]
@jocelyncardinal commented on [Thu May 23 2019](https://github.com/CAUCA-9-1-1/survip/issues/549)

**Describe the bug**
For groups of questions the minimum and maximum occurrence does not work

**To Reproduce**
Set  minimum and maximum occurrence mix max to zero ...
![Capture d’écran, le 2019-05-23 à 11.59.08.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/e9f8c003-54fc-440e-81f1-b82b7c48abde)

... in app mobile it is impossible to make zero occurence ...

![Capture d’écran, le 2019-05-23 à 12.19.32.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/7151bf09-ca7f-4cc5-b070-2f34ca7cc79f)

**Expected behavior**
Should use properly the minimum and maximum occurrence that has been set. Note that If maximum is set to zero, it would mean "no maximum limit". 

**Work around **
For the time being as work around we added an option "No item" that the user can to select ...
![Capture d’écran, le 2019-05-23 à 12.18.42.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/3305b31c-7669-4510-a044-108110df41e3)

---

@jocelyncardinal commented on [Thu May 23 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-495295922)

Idea: When the minimum occurrence is zero, we could initialy have no item. Then the user must click the "+" button to add one or click "next" to go to the next question if there is no item to be added.

---

@iamkinetic commented on [Mon May 27 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-496204619)

@philipperobertgh Dis-moi donc ce que tu penses de ça svp

---

@philipperobertgh commented on [Mon May 27 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-496206802)

SI les limites d'occurrences ne fonctionnent pas dans le mobile, il faut les corriger. Donc je suis d'accord que si l'occurrence minimale est de 0 on devrait pouvoir passer à la question suivante sans ajouter d'item. 

---

@jocelyncardinal commented on [Mon May 27 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-496211741)

Si l'occurrence minimale est de 0 on devrait pouvoir passer à la question suivante sans ajouter d'item mais il faudrait aussi conserver la possibilité d’ajouter un item (avec le petit bouton «+ » en haut à droite)

---

@iamkinetic commented on [Mon May 27 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-496229195)

Ok, on va améliorer ça aussi.  Les changements se feront uniquement dans l'application mobile, donc ce sera plus long avant que tu aies cette correction parce que je suis en train de faire la migration vers Ionic 4 et que ça me prendra encore au moins une semaine.  Lorsque ce sera terminé, on pourra faire la correction.

---

@iamkinetic commented on [Mon May 27 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-496229402)

Blocked by survip-mobile#295.

---

@iamkinetic commented on [Tue Jun 04 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-498656202)

Je ne crois pas que ce changement sera fait avant le mois de juillet.  Je dois d'abord terminer l'upgrade vers Ionic 4.

---

@jocelyncardinal commented on [Tue Jun 04 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-498662522)

Ce n’est pas une issue bloquante - Le work-around est OK et on peut attendre sans problème pour juillet

---

@iamkinetic commented on [Mon Jul 22 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-513758944)

FYI je me suis remis à l'upgrade vers ionic 4 vendredi et je travaillerai là dessus cette semaine.

---

@iamkinetic commented on [Mon Jul 22 2019](https://github.com/CAUCA-9-1-1/survip/issues/549#issuecomment-513912046)

PRE-413

**Comment by philipperobertgh** [comment]
La réponse à la question des personnes à mobilité réduite même si on a pas répondu aux questions suivantes nous averti que cela va réinitialiser la suite du questionnaire, mais les réponses ne sont pas encore entrer de plus la valeur de la réponse n'est pas affiché si le popup apparaît(voir screenshot la valeur de la case à cocher n'est pas affichée).
![image](https://user-images.githubusercontent.com/38532918/64287038-a9746900-cf2c-11e9-9639-d34cb5c0ff55.png)


La navigation back ne fonctionne pas si on n'ajoute aucune question parent.
Exemple : 13150, 118e Rue
Questionnaire -> on fait suivant en passant tous les groupes de questions(detecteur de fumée, chauffage, extincteur) le bouton suivant est disponible mais ne fonctionne pas 
![image](https://user-images.githubusercontent.com/38532918/64286940-6adeae80-cf2c-11e9-8cd9-82df37e6df93.png)

Lorsque l'on ajoute une question faisant partie d'un groupe mais que l'on ne réponds pas à toutes les questions on ne devrait pas être capable de passer au groupe suivant. Ex: répondre au premier groupe de question du détecteur -> Suivante devient disponible -> Ajout d'un deuxième detecteur devrait rendre indisponible le bouton si le 2e detecteur n'est pas compléter.
![image](https://user-images.githubusercontent.com/38532918/64287298-43d4ac80-cf2d-11e9-8e68-47b057f9afce.png)
De plus si on fait suivant à cet étape et que l'on revient sur la question ensuite, une question non répondu de plus apparait dans le groupe non rempli.
![image](https://user-images.githubusercontent.com/38532918/64287350-6f579700-cf2d-11e9-92f7-a6b2409158fd.png)

**Comment by jocelyncardinal** [comment]
**Dans le questionnaire avec les groupes avec aucun item ... la bouton  "Suivante" ne fonctionne pas correctement.**

**Exemple 1:** On clique et ca ne fait rien ...

![IMG_1502.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5acfa421-2e22-4fc1-a561-db938683ba11)


**Exemple 2:** On clique et on revient en arrière plutôt qu'a question suivante. 

![IMG_1503.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/1a2b8743-0963-45bf-b766-2e040d1961d1)

... et on reviens a la question No2 plutôt que No 4 ...

![IMG_1504.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/029c2a63-21ba-423c-aad7-793c5ca888d1)

**Pour reproduire le probleme: ** A titre informatif, l'exemple a été fait avec le bâtiment suivant ... 

![IMG_1506.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/172e19f0-c108-4232-a8e9-e1303f8644c7)

![IMG_1505.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/cec6a35c-a8f8-4155-851d-e646eaee4269)
