### ISSUE TITLE
Survey management answer and review

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#38]
Current problems on back action in the survey answer process:
 - get the right index of recursive question  
 - Do we delete all answer if user modify a previous question?
 - How do we manage the survey update ?
 - Is the method used the right one for survey answer display(slide one by one)?

**Comment by iamkinetic** [comment]
We also need to figure out what we're going to do with the answers once the inspection is acccepted.
