### ISSUE TITLE
Intégrer le component de croquis dans la page de plan d'implantation

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#75]
Intégrer le component dans la page du plan d'importation pour qu'on puisse utiliser le component de croquis sur l'image du plan. Également faire les changements nécessaires à l'API la sauvegarde.

**Comment by iamkinetic** [comment]
https://github.com/Automattic/node-canvas/wiki/installation---windows

**Comment by AudreyLR** [comment]
C'est comme ça que j'avais fait de de mon côté. Par contre, je me demande quelle serait la meilleure pratique  pour l'installation pour ceux qui vont utiliser le projet? Ajouter les informations pour l'installation au Read Me?

**Comment by iamkinetic** [comment]
Effectivement, je pense qu'il faudra penser à indiquer dans le readme du project ce qu'on doit installer.
