### ISSUE TITLE
Find out how we're going to do the offline mode

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-mobile#85]
* Is there section that should not be available when offline?
* Should we always be offline when doing an inspection?
* How and when should we handle the upload of offline data to the API?

**Comment by jocelyncardinal** [comment]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/f0eb445c-659d-4a8a-92d2-69af4492df03)

**Comment by jocelyncardinal** [comment]
![Capture d’écran 2018-12-07 à 15.08.15.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/a7c16c6f-b507-4ea4-8085-13c940d3d492)

**Comment by jocelyncardinal** [comment]
![Capture d’écran 2018-12-07 à 15.08.28.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5087045d-e455-4418-b7d1-8e5b54be45cc)
![Capture d’écran 2018-12-07 à 15.08.44.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/1ae78cbb-14a3-4d6c-863b-f2f5ded92e98)
![Capture d’écran 2018-12-07 à 15.09.38.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/5d35cda3-39d8-4c11-89a0-1104ac4822cf)
![Sans titre.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/f7a126e0-aab0-4e3d-ac6e-5a07347b661e)

**Comment by philipperobertgh** [comment]
Valider les conflits de téléchargement d'inspection:
 - Plusieurs usagers sur le même lot d'inspection
         -> désactiver le bouton de téléchargement du lot
 - Valider le téléchargement simultané(le blocage de l'inspection devra se faire dès le début du téléchargement).
 - Validation sur le commencement de l'inspection
         -> On ne pourra entrer dans une inspection que si celle-ci a été téléchargée

**Comment by iamkinetic** [comment]
À mon avis, on devrait laisser tomber l'idée du lock sur les inspections downloadées par quelqu'un:
* N'importe qui assigner à un lot pourrait downloader le lot au complet ou ses inspections individuellement peu importe que quelqu'un l'ait fait avant lui ou non.
* À la fin d'une inspection, lorsqu'on l'envoie vers le serveur, on pourrait valider qu'il n'y a pas déjà quelqu'un qui a mis fin à cette inspection:
  * On pourrait afficher un message à l'usager "Une personne a déjà complété cette inspection, voulez-vous quand même envoyer la vôtre"?

L'avantage de cette façon est qu'on supporterait que plus d'une personne parte faire le même lot d'inspection sur une tablette non connectée à internet.  Donc toutes les personnes downloaderaient le lot complet.

**Comment by jocelyncardinal** [comment]
![image.png](https://images.zenhubusercontent.com/5aeb25264b5806bc2bd1a294/f80b3be8-6435-4380-91e1-69c9e55a4bd6)

**Comment by iamkinetic** [comment]
J'ai créé l'epic et ses nombreux points:

CAUCA-9-1-1/survip-mobile#305
