### ISSUE TITLE
Anomaly: Add required information

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#86]
when adding a new anomaly if you only add a photo and go back to list there is a popup of not saved warning but the anomaly is created anyway.
We should put required information on notes or don't save the anomaly on answer no in saving popup

**Comment by iamkinetic** [comment]
Vérifier la validation de la note parce que ça semble sauvegarder même quand on a pas de note.  La validation ne se fait donc pas correctement.

Également tenir compte que les images ne devraient pas être enregistrées tant que l'anomalie n'est pas sauvegardé.

**Comment by iamkinetic** [comment]
Doublon de #96.
