### ISSUE TITLE
PNAP Display

### ISSUE THREAD

**Issue by philipperobertgh** [CAUCA-9-1-1/survip-mobile#87]
In PNAP management :
 - Adding form there a padding or footer with nothing in it in the bottom of the form
         -> remove it
![pnap](https://user-images.githubusercontent.com/38532918/40844642-7c2428f6-6582-11e8-926a-7ad491031e1a.png)

**Comment by iamkinetic** [comment]
Juste dans cette page que ça fait ça?

**Comment by iamkinetic** [comment]
À bien y penser, j'aurais envie de dire que c'est le bouton "supprimer" qui devrait être dans ce footer.

**Comment by iamkinetic** [comment]
C'est le ngIf que j'ai mis dans les ion-navbar du footer qui cause ça.  Je vais le monter d'un niveau pour carrément cacher le footer quand il n'y a rien à y mettre.
